export const textContent = {
  EN: {
    descriptionLabel: 'Description',
    urlLabel: 'URL',
    addUrlButton: 'Add URL',
    defineDataTypes: 'Define Data Types',
    objectNameLabel: 'Object Name',
    addObjectButton: 'Add Object',
    updateObjectButton: 'Update Object',
    fieldNameLabel: 'Field Name',
    fieldTypeLabel: 'Field Type',
    customTypeLabel: 'Custom Type',
    addFieldButton: 'Add Field',
    nextButton: 'Next',
    contactInfoTitle: 'Contact Information',
    emailLabel: 'Email',
    cellphoneLabel: 'Cellphone',
    backButton: 'Back',
    sendButton: 'Send',
    webScrapingService: 'Web Scraping Service',
    dataServices: 'data',
    webServices: 'web',
    about: '?',
    webScraping: 'Web Scraping',
    dataServicesTitle: 'Data Services'
  },
  ES: {
    descriptionLabel: 'Descripción',
    urlLabel: 'URL',
    addUrlButton: 'Agregar URL',
    defineDataTypes: 'Definir Tipos de Datos',
    objectNameLabel: 'Nombre del Objeto',
    addObjectButton: 'Agregar Objeto',
    updateObjectButton: 'Actualizar Objeto',
    fieldNameLabel: 'Nombre del Campo',
    fieldTypeLabel: 'Tipo del Campo',
    customTypeLabel: 'Tipo Personalizado',
    addFieldButton: 'Agregar Campo',
    nextButton: 'Siguiente',
    contactInfoTitle: 'Información de Contacto',
    emailLabel: 'Correo Electrónico',
    cellphoneLabel: 'Teléfono Móvil',
    backButton: 'Atrás',
    sendButton: 'Enviar',
    webScrapingService: 'Servicio de Web Scraping',
    dataServices: 'datos',
    webServices: 'web',
    about: '?',
    webScraping: 'Web Scraping',
    dataServicesTitle: 'Servicios de Datos'
  },
};